import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-red-500",
    "bg-green-500",
    "translate-y-[-70px]",
    "translate-y-[-71px]",
    "translate-y-[-72px]",
    "translate-y-[-73px]",
    "translate-y-[-74px]",
    "translate-y-[-75px]",
    "translate-y-[-76px]",
    "translate-y-[-77px]",
    "translate-y-[-78px]",
    "translate-y-[-79px]",
    "translate-y-[-80px]",
    "translate-y-[-81px]",
    "translate-y-[-82px]",
    "translate-y-[-83px]",
    "translate-y-[-84px]",
    "translate-y-[-85px]",
    "translate-y-[-86px]",
    "translate-y-[-87px]",
    "translate-y-[-88px]",
    "translate-y-[-89px]",
    "translate-y-[-90px]",
    "translate-y-[-91px]",
    "translate-y-[-92px]",
    "translate-y-[-93px]",
    "translate-y-[-94px]",
    "translate-y-[-95px]",
    "translate-y-[-96px]",
    "translate-y-[-97px]",
    "translate-y-[-98px]",
    "translate-y-[-99px]",
    "translate-y-[-100px]",
    "translate-y-[-101px]",
    "translate-y-[-102px]",
    "translate-y-[-103px]",
    "translate-y-[-104px]",
    "translate-y-[-105px]",
    "translate-y-[-106px]",
    "translate-y-[-107px]",
    "translate-y-[-108px]",
    "translate-y-[-109px]",  
    "translate-x-[70px]",
    "translate-x-[71px]",
    "translate-x-[72px]",
    "translate-x-[73px]",
    "translate-x-[74px]",
    "translate-x-[75px]",
    "translate-x-[76px]",
    "translate-x-[77px]",
    "translate-x-[78px]",
    "translate-x-[79px]",
    "translate-x-[80px]",
    "translate-x-[81px]",
    "translate-x-[82px]",
    "translate-x-[83px]",
    "translate-x-[84px]",
    "translate-x-[85px]",
    "translate-x-[86px]",
    "translate-x-[87px]",
    "translate-x-[88px]",
    "translate-x-[89px]",
    "translate-x-[90px]",
    "translate-x-[91px]",
    "translate-x-[92px]",
    "translate-x-[93px]",
    "translate-x-[94px]",
    "translate-x-[95px]",
    "translate-x-[96px]",
    "translate-x-[97px]",
    "translate-x-[98px]",
    "translate-x-[99px]",
    "translate-x-[100px]",
    "translate-x-[101px]",
    "translate-x-[102px]",
    "translate-x-[103px]",
    "translate-x-[104px]",
    "translate-x-[105px]",
    "translate-x-[106px]",
    "translate-x-[107px]",
    "translate-x-[108px]",
    "translate-x-[109px]",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        "twilio-red": "#F22F46",
        "twilio-ink": "#121C2D",
        "twilio-paper": "#FDF7F4",
        "twilio-mint": "#6ADDB2",
        "twilio-sky": "#51A9E3",
        "twilio-saffron": "#F2BE5A",
        "twilio-sun": "#FF7A00",
      },
    },
  },
  plugins: [],
};
export default config;
